name: Pull and Push to ACK
on:
  push:
    branches: [ "master" ]
    - name: Login to ACR with the AccessKey pair
      uses: aliyun/acr-login@v1
      with:
        login-server: "registry.cn-beijing.aliyuncs.com"
        region-id: "cn-beijing"
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWORD }}"
    - name: push ingress-nginx
      run: |
        docker pull registry.k8s.io/ingress-nginx/controller:v1.7.0
        docker tag registry.k8s.io/ingress-nginx/controller:v1.7.0 registry.cn-beijing.aliyuncs.com/tiyee/ingress-nginx-controller:v1.7.0
        docker push registry.cn-beijing.aliyuncs.com/tiyee/ingress-nginx-controller:v1.7.0
