name: Pull and Push to ACK

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.1-rootless

      - name: Docker Login to ACR
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_username }}
          password: ${{ secrets.ACR_password }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: . # Dockerfile 所在的目录
          file: ./Dockerfile # Dockerfile 的路径，如果 Dockerfile 文件名为 Dockerfile，则可以省略
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/tektona/ingress-nginx-controller:latest # 使用 latest 标签，方便更新
          build-args: | # 如果需要传递构建参数
            VERSION=v1.7.0

      # - name: Push ingress-nginx (Alternative, if you still want to pull from Docker Hub)
      #   run: |
      #     docker pull registry.k8s.io/ingress-nginx/controller:v1.7.0
      #     docker tag registry.k8s.io/ingress-nginx/controller:v1.7.0 registry.cn-beijing.aliyuncs.com/tiyee/ingress-nginx-controller:v1.7.0
      #     docker push registry.cn-beijing.aliyuncs.com/tiyee/ingress-nginx-controller:v1.7.0
